
CREATE TABLE user (
id INT(15) AUTO_INCREMENT UNSIGNED 
PRIMARY KEY NOT NULL,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
date TIMESTAMP NOT NULL,
activationurl VARCHAR(255) NOT NULL,
status ENUM(0,1) NOT NULL
)
